// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpc3IquUATw1u4Wfk1lyqREOLYrYc9Etc',
    appId: '1:10381457932:web:624efd38d770e27e360c29',
    messagingSenderId: '10381457932',
    projectId: 'antrian-puskesmas-free',
    authDomain: 'antrian-puskesmas-free.firebaseapp.com',
    storageBucket: 'antrian-puskesmas-free.firebasestorage.app',
    measurementId: 'G-7Y72Z11BK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC-1wVkp2Q-gcekCcatyloe9TgT3ir1eE',
    appId: '1:10381457932:android:7ac6ce4fa8a6913d360c29',
    messagingSenderId: '10381457932',
    projectId: 'antrian-puskesmas-free',
    storageBucket: 'antrian-puskesmas-free.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpZUN2T2_JJ8o5pr-KZFQ5UQjCvxDlDu8',
    appId: '1:10381457932:ios:2bb115d09dbe1249360c29',
    messagingSenderId: '10381457932',
    projectId: 'antrian-puskesmas-free',
    storageBucket: 'antrian-puskesmas-free.firebasestorage.app',
    iosBundleId: 'com.example.antrianPuskesmas',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpZUN2T2_JJ8o5pr-KZFQ5UQjCvxDlDu8',
    appId: '1:10381457932:ios:2bb115d09dbe1249360c29',
    messagingSenderId: '10381457932',
    projectId: 'antrian-puskesmas-free',
    storageBucket: 'antrian-puskesmas-free.firebasestorage.app',
    iosBundleId: 'com.example.antrianPuskesmas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpc3IquUATw1u4Wfk1lyqREOLYrYc9Etc',
    appId: '1:10381457932:web:83f7047594b4380a360c29',
    messagingSenderId: '10381457932',
    projectId: 'antrian-puskesmas-free',
    authDomain: 'antrian-puskesmas-free.firebaseapp.com',
    storageBucket: 'antrian-puskesmas-free.firebasestorage.app',
    measurementId: 'G-ZYZ63FBN1P',
  );
}
